apiVersion: v1
kind: Pod
metadata:
  name: threads
  namespace: threads
  labels:
    marblerun/marbletype: Threads
spec:
  imagePullSecrets:
    - name: regcred
  containers:
    - name: client-container
      image: ghcr.io/edgelesssys/threads-test:latest
      imagePullPolicy: Always
      resources:
        requests:
          memory: "1Gi"
          sgx.intel.com/epc: "1G"
          sgx.intel.com/enclave: 1
          sgx.intel.com/provision: 1
        limits:
          sgx.intel.com/epc: "1G"
          sgx.intel.com/enclave: 1
          sgx.intel.com/provision: 1
      env:
        - name: SGX_AESM_ADDR
          value: "1"
        - name: EDG_MARBLE_UUID_FILE
          value: uuid
      volumeMounts:
        - name: aesmd
          mountPath: /var/run/aesmd/
  volumes:
    - name: aesmd
      hostPath:
        path: /var/run/aesmd/
