apiVersion: "kubeflow.org/v1"
kind: "TFJob"
metadata:
  name: "d-paddles-training"
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Chief:
      replicas: 1
      restartPolicy: OnFailure
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
            - name: tensorflow
              image: ghcr.io/edgelesssys/tf-training:execve
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 5
                  memory: "12Gi"
                  sgx.intel.com/epc: "8G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
                limits:
                  sgx.intel.com/epc: "8G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
              env:
                - name: SGX_AESM_ADDR
                  value: "1"
              command:
                - "gramine-sgx"
                - "python"
              volumeMounts:
                - name: aesmd
                  mountPath: /var/run/aesmd/
          volumes:
            - name: aesmd
              hostPath:
                path: /var/run/aesmd/
    PS:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
            - name: tensorflow
              image: ghcr.io/edgelesssys/tf-training:execve
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 2
                  memory: "12Gi"
                  sgx.intel.com/epc: "8G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
                limits:
                  sgx.intel.com/epc: "8G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
              env:
                - name: SGX_AESM_ADDR
                  value: "1"
              command:
                - "gramine-sgx"
                - "python"
              volumeMounts:
                - name: aesmd
                  mountPath: /var/run/aesmd/
          volumes:
            - name: aesmd
              hostPath:
                path: /var/run/aesmd/
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        spec:
          imagePullSecrets:
          - name: regcred
          containers:
            - name: tensorflow
              image: ghcr.io/edgelesssys/tf-training:execve-worker
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  cpu: 6
                  memory: "18Gi"
                  sgx.intel.com/epc: "16G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
                limits:
                  sgx.intel.com/epc: "16G"
                  sgx.intel.com/enclave: 1
                  sgx.intel.com/provision: 1
              env:
                - name: SGX_AESM_ADDR
                  value: "1"
              command:
                - "gramine-sgx"
                - "python"
              volumeMounts:
                - name: aesmd
                  mountPath: /var/run/aesmd/
          volumes:
            - name: aesmd
              hostPath:
                path: /var/run/aesmd/
